apiVersion: v1
kind: Service
metadata:
  name: aceest-app-service
  labels:
    app: aceest-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: aceest-app