apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app
  labels:
    app: aceest-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-app
  template:
    metadata:
      labels:
        app: aceest-app
    spec:
      containers:
      - name: aceest-app
        image: sivachokkalingam1510aceest-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5