sonar.projectKey=AceFit
sonar.projectName=ACEest
sonar.projectVersion=1.0
sonar.sources=.
sonar.tests=test_logic.py,test_app.py
sonar.language=py
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/templates/**,**/*.md
